# Generated by Django 4.2.15 on 2024-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_slot', 'Can view slot/slots'), ('change_slot', 'Can change slot/slots'), ('delete_slot', 'Can delete slot/slots'), ('accept_slot', 'Can accept slot with client'), ('decline_slot', 'Can decline slot with client'), ('view_slot_action', 'Can view slot action/slot actions')],
            },
        ),
    ]
