# Generated by Django 4.2.15 on 2024-10-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistpermissions',
            options={'permissions': [('view_slot', 'Can view slot/slots'), ('add_slot', 'Can add slot'), ('change_slot', 'Can change slot'), ('delete_slot', 'Can delete slot'), ('accept_slot', 'Can accept slot with client'), ('decline_slot', 'Can decline slot with client'), ('view_slot_action', 'Can view slot action/slot actions')]},
        ),
    ]
