# Generated by Django 4.2.9 on 2024-09-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_date1_slot_datetime1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cancel type name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Consult type name', max_length=255, unique=True)),
            ],
        ),
    ]
