# Generated by Django 4.2.15 on 2024-09-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_canceltype_consulttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cost',
            field=models.FloatField(default=0, help_text='Cost for consultation'),
        ),
        migrations.AddField(
            model_name='slot',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.consulttype'),
        ),
    ]
