# Generated by Django 4.2.15 on 2024-09-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slot_cost_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cancel_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.canceltype'),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recent created'), ('QRY', 'Client query sent'), ('ACP', 'Client accepted'), ('CNL', 'Canceled')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='slot',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.CreateModel(
            name='SlotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Recent created'), ('QRY', 'Client query sent'), ('ACP', 'Client accepted'), ('CNL', 'Canceled')], default='NEW', max_length=3)),
                ('datetime', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slot')),
            ],
        ),
    ]
