# Generated by Django 4.2.15 on 2024-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slot_cancel_type_slot_status_alter_slot_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='cancel_comment',
            field=models.TextField(blank=True, default='', help_text='Cancellation - comment', null=True),
        ),
    ]
