# Generated by Django 4.2.15 on 2024-09-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reason type name', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'Recent created'), ('SGN', 'Client sign'), ('USG', 'Client unsign'), ('ACP', 'Specialist accept'), ('DCL', 'Specialist decline'), ('DLT', 'Slot destroyed')], default='NEW', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SlotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Recent created'), ('QRY', 'Client query sent'), ('ACP', 'Client accepted'), ('CNL', 'Canceled')], default='NEW', max_length=3)),
                ('comment', models.TextField(blank=True, default='', help_text='Status action comment', null=True)),
                ('datetime', models.DateTimeField(help_text='Datetime of event')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('reason_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reasontype')),
            ],
        ),
        migrations.RemoveField(
            model_name='slotquery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='slotquery',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='cancel_comment',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='cancel_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
        migrations.AddField(
            model_name='slot',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Client query is accepted by specialist'),
        ),
        migrations.DeleteModel(
            name='CancelType',
        ),
        migrations.DeleteModel(
            name='SlotQuery',
        ),
        migrations.AddField(
            model_name='slotaction',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slot'),
        ),
    ]
