# Generated by Django 4.2.15 on 2024-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reasontype_slotaction_remove_slotquery_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'Recent created'), ('SGN', 'Client sign'), ('USG', 'Client unsign'), ('ACP', 'Specialist accept'), ('DCL', 'Specialist decline'), ('DLT', 'Slot destroyed')], default='NEW', max_length=3),
        ),
    ]
