# Generated by Django 4.2.15 on 2024-10-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_slotaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotaction',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
