# Generated by Django 4.2.15 on 2024-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_spec', 'Can view specialist/specialists'), ('view_slot', 'Can view slot/slots'), ('sign_slot', 'Can sign slot'), ('unsign_slot', 'Can unsign slot'), ('view_slot_action', 'Can view slot action/slot actions')],
            },
        ),
    ]
