# Generated by Django 4.2.15 on 2024-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_user', 'Can view user/users'), ('change_user_status', 'Can change user status active'), ('view_slot_action', 'Can view slot action/slot actions')],
            },
        ),
    ]
