# Generated by Django 4.2.15 on 2024-10-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermissions',
            options={'permissions': [('view_user', 'Can view user/users'), ('change_user_status', 'Can change user status active')]},
        ),
    ]
